on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install styler
        run: R -e "install.packages('styler')"
      - name: Check formatting
        run: R -e "styler::style_dir(dry = 'on')"